name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  automation-test-job:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      # Langkah baru - Mulai server di background dan tentukan host/port yang eksplisit
      - name: Start dev server
        run: npm run dev -- --host 127.0.0.1 --port 5173 &
        shell: bash

      # Tunggu server siap dengan timeout yang lebih panjang
      - name: Wait for server to be ready
        run: npx wait-on http://127.0.0.1:5173 --timeout 60000

      # Jalankan pengujian setelah server siap
      - name: Run tests
        run: npm run test
